### ISSUE TITLE
Update BibleQuote third-party libraries

### ISSUE THREAD

**Issue by rkazakov** [BibleQuote/BibleQuote#4]
As a BibleQuote developer, I would like to update all BibleQuote third-party libraries to latest versions.

**Acceptance Criteria**:

Please update the following libraries:
- ASGSQlite3
- HTML View
- JCL
- SevenZip
- CoolTrayIcon
- TextTrayIcon
- Virtual Treeview

**Comment by rgilmutdinov** [comment]
Pull request #1 introduces the following changes to 3rd party libraries:

- **ASGSQlite3**: updated from version "Release 2006.03.C" to "Release 2009.02.A", applied unicode version;
- **HTML View**: removed dependency on TNT components;
- **JCL**: updated from version 2.2 to 2.9;
- **SevenZip**: removed deprecated API calls;
- **CoolTrayIcon**: updated from version 4.0 to 4.4, made compilable with delphi tokyo;
- **TextTrayIcon**: updated from version 1.2.0 to 1.2.1, made compilable with delphi tokyo;
- **Virtual Treeview**: updated from version 5.0.0 to 7.0;

It leaves unchanged the following components (because they are compatible with the latest delphi tokyo):
- **GDI+ Library**
- **GLibWMI**
- **Hotkey**
- **RKControls**

**Comment by rkazakov** [comment]
Completed in https://github.com/BibleQuote/BibleQuote/pull/1.
